<a href="https://colab.research.google.com/github/zubliquzaini/tensorflow2-keras-bootcamp/blob/master/Introduction_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
mylist = [1,2,3]

In [0]:
np.array(mylist)

array([1, 2, 3])

In [0]:
nested_list = [[1,2], [3,4], [5,6]]

In [0]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
np.arange(0,10) # Create number from 0 to 9. Size 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(0,11) # Create number from 0 to 10. Size 11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
np.arange(0,11,2) # Create even number ranging from 0 to 10

array([ 0,  2,  4,  6,  8, 10])

In [0]:
np.zeros((4,10)) # Create 2D matrix of zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [0]:
np.ones(3) # Create 1D matrix of ones

array([1., 1., 1.])

In [0]:
np.ones((4,4)) # Create 2D matrix of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
np.linspace(0,10,3) # Range of number evenly space

In [18]:
np.eye(5) # Diagonal matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(2) # Random number from 0 to 1

array([0.6773131 , 0.54452123])

In [20]:
np.random.rand(3,4) # Random number in matrix

array([[0.35844142, 0.64756128, 0.3774878 , 0.99417406],
       [0.3712605 , 0.83305216, 0.52462608, 0.56159861],
       [0.50083081, 0.16779015, 0.80896046, 0.39532875]])

In [21]:
np.random.randn(5,5) # Random number from standard distribution

array([[-0.1823382 , -1.28228008, -0.53616738,  1.87570986,  0.45049118],
       [-0.30754039, -1.41511242, -2.06853739, -1.47940553,  1.26313601],
       [ 0.08996905, -0.25178005, -0.02934894, -0.47291041, -0.3376559 ],
       [ 0.9993514 , -0.14888205,  0.80785351,  0.02083562, -1.34918051],
       [-0.31237752, -0.90773819, -0.60636885,  0.1914561 ,  1.44384875]])

In [23]:
np.random.randint(1,100,10)

array([55,  7, 42, 85, 34, 17, 13, 63, 72, 68])

In [24]:
np.random.seed(42) # Produce the same random number every time
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [0]:
arr = np.arange(25)

In [0]:
ranarr = np.random.randint(0,50,10)

In [27]:
arr.shape

(25,)

In [28]:
arr.reshape(5,5) # Reshape array to other from

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [30]:
ranarr.max() # Highest value in the array

39

In [31]:
ranarr.argmax() # Location of highest value

7

In [32]:
ranarr.dtype # return datatype 

dtype('int64')